# Generated by Django 4.2.7 on 2025-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('dining', 'Dining'), ('spa', 'Spa & Wellness'), ('business', 'Business'), ('recreation', 'Recreation'), ('transport', 'Transportation'), ('other', 'Other Services')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('available_days', models.CharField(blank=True, max_length=100)),
                ('available_times', models.CharField(blank=True, max_length=100)),
                ('requires_booking', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
