# Generated by Django 4.2.7 on 2025-10-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicereservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='paystack', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_notes', models.TextField(blank=True)),
                ('service_reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='services.servicereservation')),
            ],
            options={
                'verbose_name': 'Service Reservation Payment',
                'verbose_name_plural': 'Service Reservation Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
