"""
Django settings for eHospitality project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yst8ek@llag$%r@2@)l)*0178ybkf8rfzx)4#u+=_67@!d%p4g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'ckeditor',
    'ckeditor_uploader',
    'embed_video',
    'django_filters',

    # Your custom apps
    'accounts.apps.AccountsConfig',  # User accounts & authentication
    'hotel.apps.HotelConfig',  # Core hotel information
    'rooms.apps.RoomsConfig',  # Room management
    'bookings.apps.BookingsConfig',  # Reservation system
    'gallery.apps.GalleryConfig',  # Photo gallery
    'services.apps.ServicesConfig',  # Additional services
    'reviews.apps.ReviewsConfig',  # Guest reviews
    'contacts.apps.ContactsConfig',  # Contact & inquiries
    'blog.apps.BlogConfig',  # News & updates

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eHospitality.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notification_counts',
                'accounts.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'eHospitality.wsgi.application'

# settings.py
# If you want to use WebSocket for real-time notifications
ASGI_APPLICATION = 'eHospitality.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"  # Only if using file uploads
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = None  # Let CKEditor handle jQuery automatically

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'height': 300,
        'width': '100%',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# user
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = '/'

# settings for the Jazzmin dashboard
JAZZMIN_SETTINGS = {
    'site_header': "Equal Hospitality",
    'site_brand': "Equal Hotel and Restaurant",
    'site_logo': "images/jazzmin.png",
    'copyright': "Equal Hospitality (R)",

    # Inline CSS for logo resizing
    'custom_css': '''
        <style>
        .brand-link img {
            max-height: 40px !important;
            width: auto !important;
            padding: 5px !important;
        }
        </style>
    ''',
}


# ckeditor
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'codeSnippet_theme': 'monokai',
        'toolbar': 'all',
        'extraPlugins': ', '.join(
            [
                'codesnippet',
                'widget',
                'dialog',
            ]
        ),
    }
}


# SENDING BULK MAILS TO CUSTOMERS

EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'laticotechgh@gmail.com'
EMAIL_HOST_PASSWORD = 'uotrwgqvcyrngvdf'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'laticotechgh@gmail.com'

# In settings.py - FOR DEVELOPMENT ONLY
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#     EMAIL_HOST = 'smtp.gmail.com'
#     EMAIL_HOST_USER = 'laticotechgh@gmail.com'
#     EMAIL_HOST_PASSWORD = 'your-app-password'  # Use app password here
#     EMAIL_PORT = 587
#     EMAIL_USE_TLS = True
#     EMAIL_USE_SSL = False
#     DEFAULT_FROM_EMAIL = 'laticotechgh@gmail.com'