# Generated by Django 4.2.7 on 2025-10-27 17:00

import ckeditor_uploader.fields
from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='about_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
