# Generated by Django 4.2.7 on 2025-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
    ]
